/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wos_screencapture_util_Utils */

#ifndef _Included_com_wos_screencapture_util_Utils
#define _Included_com_wos_screencapture_util_Utils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wos_screencapture_util_Utils
 * Method:    rgb2YCbCr420
 * Signature: ([B[BII)V
 */
JNIEXPORT void JNICALL Java_com_wos_screencapture_util_Utils_rgb2YCbCr420
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
